stages:
- Install
- Build
- Deploy

.install_template: &install_definition
stage: Install
cache:
key: master
paths:
- node_modules/
script:
- npm install

.build_template: &build_definition
stage: Build
cache:
key: master
paths:
- node_modules/
policy: pull
script:
-npm run build
artifacts:
paths:
- build

.deploy_template: &deploy_definition
stage: Deploy
image: node:8.14.0-alpine
script:
- echo "Deploy"

install:
<<: *install_definition
environment:
name: production
only:
- master

build:
<<: *build_definition
variables:
REACT_APP_ENV: production
environment:
name: production
only:
- master

deploy:
<<: *deploy_definition
when: manual
environment:
name: production
only:
- master
